---
- name: Test Ansible Playbook
  hosts: all
  become: yes
  vars:
    database_password: "hardcoded_secret_123"  # Security issue
    api_key: "sk-1234567890abcdef"             # Security issue
    
  tasks:
    - name: Install package using shell (inefficient)
      shell: apt-get install nginx              # Performance issue
      
    - name: Create user with password
      user:
        name: testuser
        password: "{{ database_password }}"     # Missing no_log
        
    - name: Debug sensitive information
      debug:
        var: api_key                            # Security issue
        
    - name: Use deprecated syntax
      include: other_tasks.yml                  # Quality issue
      
    - name: File with wrong permissions
      file:
        path: /tmp/test.txt
        mode: 0777                              # Security issue
        
    - name: Unquoted variable
      copy:
        src: {{ source_file }}                  # Quality issue
        dest: /tmp/destination
        
    - name: Loop with deprecated syntax
      shell: echo {{ item }}
      with_items:                               # Performance issue
        - file1
        - file2
        
    - name: Shell command with user input
      shell: rm -f {{ user_input }}             # Security issue
